--- /tmp/zMfIEt_Makefile
+++ /home/ash/Web/sass.js/libsass/libsass/Makefile
@@ -227,6 +227,35 @@
 debug-shared: CXXFLAGS := -g -DDEBUG -DDEBUG_LVL="$(DEBUG_LVL)" $(filter-out -O2,$(CXXFLAGS))
 debug-shared: shared
 
+js: static
+	emcc lib/libsass.a -o lib/libsass.js \
+ 		-O3 \
+		-s WASM=1 \
+		-s EXPORTED_FUNCTIONS="['_sass_compile_emscripten']" \
+		-s DISABLE_EXCEPTION_CATCHING=0 \
+		-s ALLOW_MEMORY_GROWTH=1 \
+		-s EMTERPRETIFY=1 \
+		-s EMTERPRETIFY_ASYNC=1 \
+		-s EMTERPRETIFY_WHITELIST=@../empterpreter_whitelist.json \
+		--memory-init-file 0
+
+js-debug: static
+	emcc lib/libsass.a -o lib/libsass.js \
+		-O0 \
+		-s WASM=1 \
+		-s EXPORTED_FUNCTIONS="['_sass_compile_emscripten']" \
+		-s DISABLE_EXCEPTION_CATCHING=0 \
+		-s ALLOW_MEMORY_GROWTH=1 \
+		-s EMTERPRETIFY=1 \
+		-s EMTERPRETIFY_ASYNC=1 \
+		-s EMTERPRETIFY_WHITELIST=@../empterpreter_whitelist.json \
+		-s ASSERTIONS=1 \
+		-s SAFE_HEAP=1 \
+		-s DEMANGLE_SUPPORT=1 \
+		--profiling-funcs \
+		--minify 0 \
+		--memory-init-file 0
+
 lib:
 	$(MKDIR) lib
 
@@ -321,7 +350,7 @@
 	$(RUBY_BIN) $(SASS_SPEC_PATH)/sass-spec.rb -V 3.4 -c $(SASSC_BIN) --impl libsass --probe-todo $(LOG_FLAGS) $(SASS_SPEC_PATH)/$(SASS_SPEC_SPEC_DIR)
 
 clean-objects: lib
-	-$(RM) lib/*.a lib/*.so lib/*.dll lib/*.la
+	-$(RM) lib/*.a lib/*.so lib/*.dll lib/*.la lib/*.js
 	-$(RMDIR) lib
 clean: clean-objects
 	$(RM) $(CLEANUPS)

